### ISSUE TITLE
vpaw debug build fails on g3logger install step

### ISSUE THREAD

**Issue by jadh4v** [KitwareMedical/vpaw#16]
# Description
vpaw debug build fails on g3logger install step

```CMake
Performing install step for 'g3log'
Error copying file "D:/b/VPAWD22/g3log-build/Debug/g3loggerd.lib" to "D:/b/VPAWD22/g3log-install/lib/g3loggerd.lib"
```

Install step of 'g3log' expects the built library file to be `g3loggerd.lib` in debug mode, but it is created as `g3logger.lib`

**Comment by jcfr** [comment]
Is this happening building https://github.com/KitwareMedical/vpaw/pull/15 ?

**Comment by jadh4v** [comment]
Ok, let me verify. I'll update you here.

**Comment by jadh4v** [comment]
Its definitely happening for the current master, so after #12 was merged, but not sure if it was happening before.

**Comment by jcfr** [comment]
That is very helpful comment as it indicates which version of iMSTK is associated with the problem.

**Comment by Leengit** [comment]
IMSTK is no longer a dependency of VPAW; see Pull Request #33.  At least for now, this issue is moot.  I'll close this issue as "not planned" so that we can easily reopen it, should it again become moot.
