### ISSUE TITLE
Make VPAWVisual and VPAWModel modules more apparent

### ISSUE THREAD

**Issue by Leengit** [KitwareMedical/vpaw#25]
These modules should be made available via obvious buttons, be in lists of favorite modules, etc.

**Comment by Leengit** [comment]
Currently (once pull request #26 is merged) the way to access the main modules, `VPAWVisualize` and `VPAWModel`, is to click on the gear, disable Hide Slicer Interface, click on the drop down for selecting modules, find the menu named `VPAW`, and select `VPAW Visualize` or select `VPAW Model`.

I would instead like to add two buttons to the `Home` module; clicking on one switches immediately to the `VPAW Visualize` module, the other to the `VPAW Model` module.  I can make the buttons but __am seeking an example of a Python function__ that switches the 3D Slicer module for the user.  I can then mimic that and `connect` it to `clicked(bool)` for my new buttons.

**Comment by ebrahimebrahim** [comment]
> I can make the buttons but **am seeking an example of a Python function** that switches the 3D Slicer module for the user.

See https://slicer.readthedocs.io/en/latest/developer_guide/script_repository.html#switch-to-a-different-module
