### ISSUE TITLE
ENH: Add vpaw_USE_IMSTK as cmake flag

### ISSUE THREAD

**Issue by Leengit** [KitwareMedical/vpaw#38]
As suggested at https://github.com/KitwareMedical/vpaw/pull/33#issuecomment-1656082318 by @jcfr (see "Pull Request 1"), we can support including SlicerIMSTK optionally by adding a cmake flag to indicate inclusion.

In Pull Request https://github.com/KitwareMedical/vpaw/pull/33, we removed SlicerIMSTK because it would not build under Microsoft Windows due to a C++ version issue: 3D Slicer wants C++17 but IMSTK wants C++14.  Unfortunately, that fix disables inclusion of IMSTK on other operating systems too.  With the present issue implemented, the user can include or not include IMSTK as is best for the user.

**Comment by ebrahimebrahim** [comment]
Update: We decided to remove any possible use of IMSTK as it will not be part of VPAW.
